### ISSUE TITLE
Generate distilled target samples by the autoregressive model, i.e., set --gen-subset train while decoding.

### ISSUE THREAD

**Issue by hanyaqian** [lemmonation/jm-nat#1]
你好，我是从ACL2020过来的，：），想问下`Generate distilled target samples by the autoregressive model, i.e., set --gen-subset train while decoding.`的作用是什么呀？

目的是输出 `distilled training set` 吗？ 那`--gen-subset train` 是在AT模型训练过程中指定的？

**Comment by hanyaqian** [comment]
`Train our model on the distilled training set. For example, on the IWSLT14 De-En task:` 中的$DATA_DIR 应该和步骤1（训练AT模型）中的数据路径是不一样的吧？ 道理上讲应该是步骤2 的输出路径。步骤2应该是在推理过程中指定了参数，`--gen-subset`, 是这样吗？
```
python interactive.py $data_dir \
  --input $decode_from_file --output $decode_to_file \
  --wp --topk_wp_cands 10 --topk_freq_word_cands 10 --path $model_file --beam 5 --max-len-a 1 --max-len-b 50 --beam 5  --lenpen 0.6 \
  --gen-subset train
```
我发现，加人`  --gen-subset train` 参数的前后，输出是一样的呀

**Comment by lemmonation** [comment]
Hi, you should use `python generate.py` and omit the `--input` flag. If you add this flag then the model will generate target sentences according to the specified `$decode_from_file`.
