### ISSUE TITLE
报一个bug：source中的mask_index和为词表中第一个词的index

### ISSUE THREAD

**Issue by hanyaqian** [lemmonation/jm-nat#2]
fairseq/data/xy_noisy_language_pair_dataset.py 的XYNoisyLanguagePairDataset 中

src_item: tensor([ 9,  4<,  4<,  8, 11,  8,  2]) ，  箭头指示为词表中的词， 代码位置`https://github.com/lemmonation/jm-nat/blob/master/fairseq/data/xy_noisy_language_pair_dataset.py#L126`

source: [4<, 4<, 4, 8, 11, 8, 2]  , 箭头所示为输入mask掉的词, 代码位置`https://github.com/lemmonation/jm-nat/blob/master/fairseq/data/xy_noisy_language_pair_dataset.py#L174`
    
source_output [9, 4, 1, 1, 1, 1, 1]， 代码位置，`https://github.com/lemmonation/jm-nat/blob/master/fairseq/data/xy_noisy_language_pair_dataset.py#L177`

问题是，source 中的mask_index和词表index混淆了
 
src_item 是输入,  source 是mask_encoder后的结果，会看到，mask索引（4）和src_item 中真实词的索引（4）是一样的

**Comment by lemmonation** [comment]
Please describe your problem more accurately

**Comment by hanyaqian** [comment]
为什么预测的时候，不和训练过程一致，把encoder端mask掉呢？

**Comment by lemmonation** [comment]
just like dropout, it is unnecessary to do so in inference.
